### ISSUE TITLE
Is this specific output possible?

### ISSUE THREAD

**Issue by branchow** [MCluck90/simple-ssh#12]
I've created a bash script which installs the Teamspeak 3 software. Post installation, after starting the server for the first time, there is output that is provided to the end user.

When using Simple-SSH I noticed that that particular block / output isn't logged and streamed back. I've attached an image of what it looks like.

![screenshot 2014-11-24 16 05 23](https://cloud.githubusercontent.com/assets/5105120/5173119/ca59a21e-73f3-11e4-81f8-737dfcec9c93.png)

Is there any possible way of capturing this output and providing it to the end user?

**Comment by dopyoman** [comment]
@branchow I have a similar problem. I need to get the output of the screen back to the client. What screen command did you use?

**Comment by branchow** [comment]
You can execute a command such as 

> screen -S YOURCOMMANDHERE

And your output will be sent back to the client. Let me know if that works!

**Comment by dopyoman** [comment]
Not quite. I'm guessing what im trying to do is slightly differnet then what you did. Your script at the ended echoed out that formatted message and that is what you wanted to capture. I'm trying to pipe back to the client the ouput stream from the provision script. But I think ssh-exec lets you pipe the stdout stream back. so I'm testin that now.
