### ISSUE TITLE
Weird variable scoping and/or value issue in exec string

### ISSUE THREAD

**Issue by thepuzzlemaster** [MCluck90/simple-ssh#15]
I've got a weird thing happening in my app.

I'm building a batch deployment tool which will connect to numerous raspberry pi boards and check a code version, and then pull down new code if available.

Everything is working great except for one strange thing.

I have a global variable called latestVersion which gets set to the latest version of software. within the out and exit functions, it has the correct value. However, when I reference it within the exec command string, it reverts to the original value. 

I've also tried storing the variable in an object (data.latestVersion) thinking that if it was a scoping issue, it would throw an error since data would be undefined if it didn't exist in a specific scope. However, that behaved identically.

I will attempt to create a simplified version of my code so you can reproduce.

The ip address won't work for you, but hopefully you have something you can use to test. 

````
var Ssh = require('simple-ssh');

var singleIp = ['10.119.73.74'];

var ssh = new Ssh({
  host: singleIp[0],
  user: 'pi',
  pass: 'raspberry'
});

var latestVersion = '0.05';

ssh.exec('echo "changing latestVersion"', {
  exit: function() {
    // setting the latestVersion to a new value
    latestVersion = '0.1';
    console.log(latestVersion, 'should be: 0.1');
  }
}).exec('echo "' + latestVersion + '" > current_version', {
  exit: function() {
    console.log('current_version file written');
    console.log('latestVersion', latestVersion);
    // latestVersion still logs out as 0.1
  }
}).exec('cat current_version', {
  // value used in current_version was still 0.05
  out: function(stdout) {
    console.log('current_version:', stdout);
  },
  exit: function() {
    console.log('exiting final command!');
  }
}).start();
````

**Comment by MCluck90** [comment]
The problem is that `'echo "' + latestVersion + '" > current_version'` is evaluated before any commands are run so the actual string you're producing is probably more like `echo "" > current_version`.

In this case, you will need to add the commands after the fact like this:

```javascript
ssh.exec('echo "changing latestVersion"', {
  exit: function() {
    // setting the latestVersion to a new value
    latestVersion = '0.1';
    console.log(latestVersion, 'should be: 0.1');
    ssh.exec('echo "' + latestVersion + '" > current_version', {
    ...
```

It all has to do with when JavaScript evaluates values. Hope this helps!

**Comment by thepuzzlemaster** [comment]
Yes, that makes a lot of sense. Thanks very much for the explanation. It looks like this should work!
