### ISSUE TITLE
Update ssh2 to latest release (0.4.3)

### ISSUE THREAD

**Issue by Toddses** [MCluck90/simple-ssh#18]
The latest release adds a bunch of enhancements and fixes.

**Comment by Toddses** [comment]
Been working on this a bit. So far what I've learned is `Client = require('ssh2').Client` is the new preferred method to pull in an ssh2 client session. Also `exit` is no longer the event emitted when the connection is closed. Its now `close`. There is one other issue I'm bumping into where an error is generated on some commands when trying to use agent forwarding. Let me get that fixed and I'll issue a PR.

**Comment by Toddses** [comment]
Looks like the agent forwarding issue is an ssh2 issue (mscdex/ssh2#227). Will hold off until they have a chance to take a look at it.

**Comment by MCluck90** [comment]
Thanks for bringing this to my attention. I personally don't have time to implement the update at this moment but I can try to look at it when I find some free time in the coming weeks.

**Comment by Toddses** [comment]
I can issue a PR for this when ssh2 gets their next release out. With the latest release (0.4.3) there's a bug where sending multiple commands in one session causes agent forwarding to trigger an error. They have already fixed it in master, it just needs to make it into a release. Other than that it is a super simple update with only the changes I referenced above.

**Comment by mscdex** [comment]
To clarify, `exit` is still emitted for remote processes if the server sends it. The semantics of `exit` and `close` are just like node.js child processes: `exit` is emitted when the process actually exits but `close` is emitted after the process has exited but no more output will be received.

**Comment by MCluck90** [comment]
Updated to v0.5.0 with ac0fae3.
