### ISSUE TITLE
No response if My connect failed

### ISSUE THREAD

**Issue by arthurtalkgoal** [MCluck90/simple-ssh#19]
Hi, my nodejs sends ssh exec to the client servers,
And the scripts itself succeed. 

However, I found that for a new servers which haven't updated the sshd to allow Root, it failed silently, nothing appears in the console.

It is very easy for me to update the sshd_config, however,

**I wonder how can I know a log or make sure a ssh connect doesn't failed quitely**?

```
   ssh.exec("echo \"" + process_public_key + "\" > /tmp/process.pub", {
          out: console.log
    })
    .exec("su deploy -c `cat /tmp/process.pub >>  /myuser/.ssh/authorized_keys`", {
        out: function(stdout) {
            console.log(stdout);
        }
    })
    .exec("rm /tmp/process.pub")
    .start();
console.log("finished set keys");


```

**Comment by MCluck90** [comment]
You can detect any errors, including failing to connect in the `error` event. So setup a handler like this and you can handle those issues in anyway you want.

```javascript
ssh.on('error', function(err) {
  // Do some stuff
});
```
