### ISSUE TITLE
Private Key errors

### ISSUE THREAD

**Issue by cohix** [MCluck90/simple-ssh#22]
Hello,
I am having an issue with private key authentication, wherein keys without properly escaped newlines cause a failure. I am fairly certain this is the issue, and if so, could you please advise on how to properly escape the private key before using it with simple-ssh

The error I receive is:
```[Error: Incorrect passphrase: Error: privateKey value does not contain a (valid) private key]```

Thank you

**Comment by MCluck90** [comment]
Without knowing exactly what the issue is, it's impossible to say. If your key contains `\n` in it then you could easily swap them out with

```javascript
key = key.replace('\\n', '\n')
```
