### ISSUE TITLE
Doctype error

### ISSUE THREAD

**Issue by JimiSpire** [MCluck90/simple-ssh#23]
Following the simple examples over on https://www.npmjs.com/package/simple-ssh, an error is triggered. Here is my code:

		var ssh = new SSH({
	    host: 'me@myhost.net',
	    user: 'me',
	    agent: process.env.SSH_AUTH_SOCK,
	    agentForward: true
		});
		ssh.exec('echo', {
	    args: ['$PATH'],
	    out: function(stdout) {
	        console.log(stdout);
	    }
		}).start();

Here is the error:

 While building the application:
   node_modules/simple-ssh/node_modules/xtend/node_modules/is-object/test/static/index.html:1: Can't set DOCTYPE
   here.  (Meteor sets <!DOCTYPE html> for you)

=> Your application has errors. Waiting for file change.

**Comment by MCluck90** [comment]
This seems to be a problem running the old tests in [is-object](https://github.com/ljharb/is-object/blob/0a151eac357b528bb27d23af362859db446cf688/test/static/index.html), which is a dependency of xtend, related to how you're running your Meteor app. Sorry, I'm not familiar enough with Meteor to help. Although I appreciate you bringing to my attention that the version of [xtend](https://github.com/Raynos/xtend) is out of date.

**Comment by JimiSpire** [comment]
Is there a way i could bypass the xtend module?

**Comment by MCluck90** [comment]
I just publish v0.8.4 which has the updated xtend module. If you install the new version of simple-ssh then you shouldn't see that problem anymore. But be aware that you may see future problems because it looks like you have some sort of build process which scans for HTML files and attempts to build them. At least that's what it looks like based on the error message.

If that's true, you'll want to change which files it tries to build you are aren't accidentally building files inside of your node_modules/ folder.

**Comment by JimiSpire** [comment]
Yes, lots a new errors. One of which:
ReferenceError: exports is not defined

Too bad, i think i'll just remove the module.

**Comment by MCluck90** [comment]
What sorts of errors? I can't imagine updating xtend caused any inherit bugs in simple-ssh but I'd like to know if it did.

**Comment by JimiSpire** [comment]
Well, i'm building with Meteor so its all Meteor related errors.

One says:

ReferenceError: exports is not defined
at app/node_modules/simple-ssh/node_modules/ssh2/node_modules/readable-stream/node_modules/core-util-is/lib/util.js:27:1
at app/node_modules/simple-ssh/node_modules/ssh2/node_modules/readable-stream/node_modules/core-util-is/lib/util.js:109:3

**Comment by MCluck90** [comment]
Gotcha.If I understand [the documentation correctly](http://docs.meteor.com/#/basic/filestructure) then it only tries to build things in the `/client` (again, I haven't used Meteor so I could be wrong). If that is the case, then everything should work fine as long as `node_modules` isn't in the `client` folder.

**Comment by JimiSpire** [comment]
Ok, i reinstalled simple-ssh but with the -g flag this time.
And then i call it with SSH = Npm.require('simple-ssh'); in my app.

Doesnt work.

Error: Cannot find module 'simple-ssh'

**Comment by MCluck90** [comment]
That's because you installed it as a global module. That means that theoretically it's available in the command-line (except that simple-ssh doesn't have a command-line interface), not that it's available to your project. You'll need to install it normally to access it with `require('simple-ssh')`.

**Comment by JimiSpire** [comment]
The way you explain it now is the way that i installed it in the first place, and that caused errors with the Doctype thing.

So, i've reinstalled simple-ssh without the -g flag, as normally.
So it installed within my meteor project. But i moved the directory manually to the .meteor server-lib directory, where we can find other libs like fibers, chalk, eachline, semver, etc.

The exact path is:
~/.meteor/packages/meteor-tool/.1.1.1.bsqoac++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules

And in my project, on meteor server, i call it like so:
SSH = Npm.require('simple-ssh');

Now it doesnt throw any errors anymore. Not sure if it'll work though. I'll test it later and come back with the results.

Thanks.

**Comment by MCluck90** [comment]
Hope that worked! Let me know if there's anything else I can help with.

**Comment by JimiSpire** [comment]
Worked fine!

**Comment by JimiSpire** [comment]
Well, the down side is that each time i "meteor update", i have to move back the simple-ssh package in the new version's node_module directory.

Bad.
