### ISSUE TITLE
Like #11, I can't iterate

### ISSUE THREAD

**Issue by tchoyy** [MCluck90/simple-ssh#25]
Hi,

I follow your answer in issue #11 

Here is my code :

```
var SSH = require('simple-ssh');

function createConnection(config){
    var myssh = new SSH({
      host: config.host,
      user: config.user,
      pass: config.pass
    });
    myssh
      .exec('nproc',{
        out:function(stdout){
          console.log(config.host+" : "+stdout);
        }
      }).start();
}

    var config = [{
      host: 'server1',
      user: 'myuser1',
      pass: 'mypass1'
    },{
      host: 'server2',
      user: 'myuser2',
      pass: 'mypass2'
    }];

    for (var i=0;i<config.length;i++){
      createConnection(config[i]);
    }
```

The result is only :

server1 : 24

It seems that the second connection does not work at all and is not started.

I installed simple-ssh from npm and I use nodejs v0.10.32

Thanks for your help

**Comment by MCluck90** [comment]
Have you tried listening for errors to see if something is going wrong?

```js
myssh.on('error', function(err) {
  console.log(err);
});
```

**Comment by tchoyy** [comment]
Ok my fault, It was a sshd mistake configuration.

On my second server in sshd_config, there was :

PasswordAuthentication no

Thanks.

**Comment by MCluck90** [comment]
Glad you sorted it out. :+1:
