### ISSUE TITLE
Call synchronously or any proper way to detect end of response ?

### ISSUE THREAD

**Issue by goforgold** [MCluck90/simple-ssh#27]
Is there any possible way to execute ssh commands synchronously or if that's not possible how can I detect if a command execution is completed ..?

I see, callback `out` is called multiple times and I am not being able to figure out a way to find the end of the response.

Please help.

**Comment by MCluck90** [comment]
It isn't possible to call them completely synchronously but you can perform any number of commands in order. To detect when a command has completed, you use an `exit` event handler.

```javascript
ssh.on('some-command', {
  exit: function() {
    // command is complete
  }
});
```

**Comment by goforgold** [comment]
`ssh.on` or `ssh.exec` ..?

**Comment by MCluck90** [comment]
Sorry, I meant to type `exec`.

**Comment by goforgold** [comment]
Thanks, it worked.
