### ISSUE TITLE
 exit:function(code , stdout , stderr) no stdout when pty is true

### ISSUE THREAD

**Issue by wahaha2099** [MCluck90/simple-ssh#30]
when set the pty to true , the exit method return no stdout and stderr .
ssh.exec(req.body.command, {
         pty:true,
        out: function(stdout) {
            console.log('in stdout ' + stdout);
         },
         err:function(stderr){
             console.log('in stderr ' + stderr);
         },
         exit:function(code , stdout , stderr){
             console.log('exit ' + code);
             console.log('exit stdout ' + stdout);
         }
     }).start();

**Comment by MCluck90** [comment]
That's not true for the general case. I specifically show a case of it working in the example code. There must be something wrong with the command you're running or how you're running simple-ssh.

**Comment by CarlosRuizAscacibar** [comment]
First of all thank you for making this module. I have more or less the same problem:


function callback(parameter1, parameter2, parameter3){
  console.log(parameter1+'  ' + parameter2+ '  ' + parameter2);
}
ssh.exec('echo "hello world" ',{
      out:callback
    }).start();
ssh.exec('echo "hello world" ',{
      exit:callback
    }).start();

The first call prints in the console hello world, while the second one only prints the exit code 0 and does not print 'hello world'.

Note that I dont have the pty flag set to true.

**Comment by MCluck90** [comment]
Sorry I haven't replied, I've been looking in to this off and on over the last 4 days. That's a very strange bug. I'll continue to look into it as I find time. Thanks for bringing it to my attention.
