### ISSUE TITLE
using passphrase doesn't work with github enterprise

### ISSUE THREAD

**Issue by quocvu** [MCluck90/simple-ssh#31]
I am using this to make an ssh connection to github enterprise. I'd like to point out 
- the doc contains a `passphrase` config param, but it is being ignored.  The code uses the `pass` config param instead.
- when I set the following 2 params `user, key, pass` (pass contains the passphrase),   I get the following error "Error: Authentication failure. Available authentication methods: publickey"

**Comment by MCluck90** [comment]
You're right. Sorry, as you may have noticed I haven't had the time to fix this issue. If you create a fix for it, I'll be happy to merge it in.

**Comment by MCluck90** [comment]
I'm no longer actively working on this project and will be closing the issue. If anyone comes up with a solution and submits a pull request, I will merge it.
