### ISSUE TITLE
repeat call to callback

### ISSUE THREAD

**Issue by quocvu** [MCluck90/simple-ssh#32]
I am putting a simple print statement in the `out` and the callback is being executing multiple times.  The command I am running returns a filepath and that is a single line output.  Any idea what could be causing this?  There is a loop outside of ssh.exec though and I am using async.each() for that.

```
ssh.exec(cmd, {
    out: function(stdout) {
      var path = new String(stdout);
      console.log(path.trim());      
    },
    err: function(stderr) {
    }
  })
  .on('error', function(err) {
  })
  .start();
```

**Comment by MCluck90** [comment]
Yes, the callback will be executed multiple times if you have any kind of looping mechanism. What's the problem exactly?

**Comment by quocvu** [comment]
Within each iteration of the `async.each()` the callback executes times.  

For example the array we are looping over with `async.each()` has only 6 elements, which then causes `ssh.exec()` to be called 6 times.  However the callback is executed like 40 times producing 40 lines of log.

It seems to me, the callback executes when it get a bit for data coming to stdout, then executes again when getting another chunk of data. Is that the expected behavior?  If that is the case, how can I get the entire stdout and process/parse it in one shot?

**Comment by MCluck90** [comment]
That is the expected behavior. To get the entire stdout at once, create an `exit` handler.

```javascript
ssh.exec(cmd, {
     exit: function(exitCode, stdout, stderr) {
         console.log(stdout);
     }
})
.start();
```

**Comment by quocvu** [comment]
I tried that as well and I got the same result. The callback of `exit` is executed more than 6 times.

**Comment by MCluck90** [comment]
I can't help anymore without knowing more about your setup. exit only runs
once when the command completes so there is something else wrong with how
you're using it.
