### ISSUE TITLE
Keep connection alive

### ISSUE THREAD

**Issue by untitledlt** [MCluck90/simple-ssh#33]
As I see in documentation: 
**end(): Ends the SSH session (this is automatically called at the end of a command queue).**
after `.exec` connection is closed. Is it possible to keep connection alive so I could reuse it later without reconnecting to SSH server?

**Comment by MCluck90** [comment]
As it's currently designed, that's not currently possible. I can imagine ways of hijacking the connections `end` function if you really need to do that but it'd be a hack.

```javascript
var connection = ssh._c;
var oldEnd = connection.end;
connection.end = function() {
    connection.end = oldEnd;
    // Do some other stuff
};
```

**Comment by fiote** [comment]
I would really appreciate a way to keep it open.

**Comment by fiote** [comment]
I second this issue/request. I would love to have this implemented. Thanks!

**Comment by MCluck90** [comment]
I'm no longer actively working on this project. For now I'm closing the issue but if someone puts forward a pull request with this functionality, I'll happily accept it.
