### ISSUE TITLE
no timeout response?

### ISSUE THREAD

**Issue by AlfonsoJS** [MCluck90/simple-ssh#34]
I love simple-ssh, a great module, but how can I get a response if I get timeout?
It is possible to set the timeout but there is no event or key that let you know that there is a timeout
something like this:

timeout: function(msg) {
    console.log('sorry, timeout: ', msg);
}

or

ssh.on('timeout', function(msg) { console.log('sorry, you have a timeout: ', msg); });

**Comment by MCluck90** [comment]
Somehow I completely failed to answer you over a year ago. Sorry about that. I hope you've sorted it out. I'm no longer actively working on this project so I'll be closing this issue. Feel free to check out [the ssh2 module](https://github.com/mscdex/ssh2) that this is a wrapper for for more information.
