### ISSUE TITLE
Run multiple commands? 

### ISSUE THREAD

**Issue by viperbmw69** [MCluck90/simple-ssh#35]
I would love to be able to use this to replace my perl modules. 

I need to be able to log into Network Devices and run commands and parse the output. 

Is it possible to run more then one command on the target host? Also how would I run through a loop or hosts from say a file?

Thanks

**Comment by viperbmw69** [comment]
This is a snip of the code i am using 

var SSH = require('simple-ssh');
var none;
var ssh = new SSH({
    host: '10.254.126.5',
    user: 'user',
    pass: 'pass'
})
   .exec('show ver', {
        out: console.log.bind(console)
    })
    .exec('show ip int br', {
        out: console.log.bind(console)
    })
    .start();

**Comment by MCluck90** [comment]
What do you mean by run more than one command? You're doing that in your examples. If you mean within one `exec` call then you can use something like `&&` to run the next command if the first one is successful.

```javascript
ssh.exec('cmd1 && cmd2', { ... })
```

As for looping, you could store yours hosts in a JSON file in whatever format you want then load it in the Node (easiest way is using `require` but if you plan to change the file then re-open it, use the `fs` module). Then it's as simple as doing a for loop over your data, creating an SSH instance, and running your commands.

**Comment by viperbmw69** [comment]
Thank you so much for the quick response. If the code above is working I am not sure why I am not getting the output to the console when ran. I only get the first commands output not the second. Also what is the best way to collect the output into a variable so that I can parse it later? 

I am pretty familiar with perl I have used it for years for this. Normally I would use the module to put each line of the output from the command into an array as a line of "string" then I would call the line and parse it with a 
 foreach $_ (@Array) {
    //code
 }

What is the equivalant in node.js? 

Thank you for helping me with this I am new to node and want to learn it as it looks very promising.

**Comment by viperbmw69** [comment]
output is below


prc1514@hopper2:~$ cat test1.js
var SSH = require('simple-ssh');
var none;
var ssh = new SSH({
    host: '10.254.126.5',
    user: 'prc1514',
    pass: '********'
})
   .exec('show ver', {
        out: console.log.bind(console)
    })
    .exec('show ip int br', {
        out: console.log.bind(console)
    })
    .start();
prc1514@hopper2:~$ node test1.js 

       Legal Notice to Users
       This system is limited to access by company employees only.
       Access by others is unauthorized and prohibited by law.


Cisco IOS Software, 2800 Software (C2800NM-SPSERVICESK9-M), Version 15.1(4)M5, RELEASE SOFTWARE (fc1)
///  Output ///
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2012 by Cisco Systems, Inc.

**Comment by MCluck90** [comment]
I don't know what to tell you because that's going to be dependent on how your system is setup. You might try running both commands using the `&&` operator just to verify that both commands can be run.

**Comment by MCluck90** [comment]
Due to inactivity, I'm going to assume this issue has been resolved.
