### ISSUE TITLE
Pass executed command to callback

### ISSUE THREAD

**Issue by blindbox** [MCluck90/simple-ssh#36]
As the title say, can we have the executed command passed to the callback? This is pretty useful in debugging. I had such a use just recently.

For example:-

```
ssh.exec('echo "Hello World"', {exit: function(a,b,c, command) {
  console.log(command); // prints 'echo "Hello World"' without the single quotes.
}}).start();
``
```

**Comment by MCluck90** [comment]
Sorry I never got back to you. I don't have any intention of adding that to this module. I'm no longer actively working on this project so I'll be closing the issue.
