### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by Xsmael** [MCluck90/simple-ssh#4]
Hi! I just tried your app on windows with the example you gave, but nothing appears.

**Comment by focalism** [comment]
I also meet the problem,connect a linux from win7,but neither a console log out or mistakes

**Comment by MCluck90** [comment]
Hi @focalism. Without more information, I'm afraid I can't help. You could try hooking up `console.log` to the `err` property like in this example:

```js
ssh.exec('this-does-not-exist', {
    err: function(stderr) {
        console.log(stderr); // this-does-not-exist: command not found
    }
}).start();
```

but without any error information, there's literally nothing I can do for you.
