### ISSUE TITLE
ssh2 error

### ISSUE THREAD

**Issue by tpham1** [MCluck90/simple-ssh#42]
ssh2 ver 0.5.0 fixes 'connection error: Error: Disconnected by host (PROTOCOL_ERROR): Packet integrity error',while latest simple-ssh still depends on ssh2 ver 0.3.6.

Would you please update simple-ssh ?

Great pakage,
.t

**Comment by MCluck90** [comment]
Thanks, I'm glad you like it.

I just published v0.9.0 the other day (ac0fae3) which uses ssh2 v0.5.0. Try updating your simple-ssh dependency.

**Comment by MCluck90** [comment]
Closing this since it's already been updated.
