### ISSUE TITLE
Is there a way to connect using an identity file?

### ISSUE THREAD

**Issue by rohithpr** [MCluck90/simple-ssh#45]
Is there a way to do this: `ssh -i identity_file_name user@host`?

**Comment by MCluck90** [comment]
Not exactly like that, no. You can use a private key with the `key` configuration option but you can't specify an identity file. If there is a way of providing that option to the ssh2 module, and I have time to work it out, I'll gladly add it though.

**Comment by vedharish** [comment]
@rohithpr You can simply do this -

```node
var ssh = new SSH({
  host: 'localhost',
  user: 'user',
  key: require('fs').readFileSync('/path/to/private/id_rsa'),
  passphrase: 'passphrase_for_private_key'
});
```

**Comment by MCluck90** [comment]
Hopefully the above solution works well for you. For now, I'm closing the issue due to inactivity.
