### ISSUE TITLE
[MAC OS X] .exec does nothing

### ISSUE THREAD

**Issue by camilleeyries** [MCluck90/simple-ssh#47]
Hey ! I have a ssh server that is running on my mac for test purpose, but I can't access to it via this framework...
Here is my code :
```js
var SSH = require('simple-ssh');
 
var ssh = new SSH({
    host: '127.0.0.1',
    user: 'myUsername',
    pass: 'TheRightPassword'
//    passphrase: 'TheRightPasswordToo'
});

ssh.exec('echo $PATH', {
	out: function(out) {
		console.log(out);
	},
	err: function(err) {
		console.log('error: ' + err);
	}
});

sshh.on('error', function(err) {
    console.log('Oops, something went wrong.');
    console.log(err);
    ssh.end();
});
```
When I run this script, it does nothing on my mac. I tried with other commands ( like mkdir )...
Thx.

**Comment by MCluck90** [comment]
Are you seeing any errors in your console? It looks like you're typoing the variable name at the end. (`sshhh` should be `ssh`)

**Comment by camilleeyries** [comment]
No i does not seen any error...
Ive modified the script before posting it because i was believing
that changing the name can be something x) 
( i don't know if you understand me x) )
I have replaced this with another module ( ssh-exec ) but it is strange...

**Comment by TakahashiNZ** [comment]
aren't you missing the .start() required to kick everything off?

**Comment by camilleeyries** [comment]
👍
