### ISSUE TITLE
password based authentication doesn't work on Mac

### ISSUE THREAD

**Issue by mysticflute** [MCluck90/simple-ssh#48]
On OS X El Capitan, trying to authenticate with a password always fails with this error:
"Error: All configured authentication methods failed"

I can ssh normally from the command-line with my password so I know that the host, username and password is correct. After doing some digging, I found that this issue was logged for ssh2 itself here:
https://github.com/mscdex/ssh2/issues/238

Basically, when calling connect on ssh2 it needs the tryKeyboard param as true and an implementation for the keyboard-interactive event. I see the option to specify the keyboard-interactive event using 'on', , but no way to specify the tryKeyboard param?

**Comment by MCluck90** [comment]
Sorry I never helped you out with this. I'm no longer working on this project and will be closing the issue. Since this is just a wrapper of [ssh2](https://github.com/mscdex/ssh2), I'd suggest looking there if you have a use-case which is not handled here.
