### ISSUE TITLE
simple-ssh doesnt work for link local ipv6 address

### ISSUE THREAD

**Issue by devdil** [MCluck90/simple-ssh#50]
When i tried ssh to a link local ipv6 address, it reports of following error:
ERROR: connect EINVAL

Note: hostname was passed as ipv6%interface

**Comment by MCluck90** [comment]
I couldn't tell you why it isn't working without some sort of sample code. But I'm no longer working on this project and will be closing the issue. Since this is just a wrapper of [ssh2](https://github.com/mscdex/ssh2), I'd suggest looking there if you have a use-case which is not handled here.
