### ISSUE TITLE
change directory command is not working

### ISSUE THREAD

**Issue by sikarwarsanjeev** [MCluck90/simple-ssh#53]
I used cd command to change directory for remote server as below and it is not changing the directory.

var SSH = require('simple-ssh');
 
var ssh = new SSH({
    host: 'remote_server_ip',
    user: 'username',
    pass: 'password'
});
 
ssh.exec('cd /home/etc/sanjeev', {
    out: function(stdout) {
        console.log(stdout);
    }
.exec('ls', {
    out: function(stdout) {
        console.log(stdout);
    }
}).start();

So in last 'ls' is not listing files/directory from /home/etc/sanjeev but listing from /home/sanjeev.

**Comment by sikarwarsanjeev** [comment]
As workaround i am passing baseDirectory to cunstructor to change the directory.

**Comment by MCluck90** [comment]
Sorry, that's how it works. Each command is sent separately and so it returns to the base directory before each command. That's exactly why the `baseDir` option exists.
