### ISSUE TITLE
Fix on stream

### ISSUE THREAD

**Issue by jb92130** [MCluck90/simple-ssh#55]
Hello,

I'm using your lib and sometimes, I execute command with a big result. Your line 104 cut the result because of this line :
**Line 104** `stream.on('exit', function(code) {`
The handle 'exit' on a stream doesn't wait until the end of result.

I suggest you to change by this line and your user could use your lib without bug.
**Line 104** `stream.on('close', function(code) {`

Kind regards,

JB.

**Comment by MCluck90** [comment]
Thanks for the catch! If you make a pull request with that change, I'll happily merge it.

**Comment by jb92130** [comment]
You're welcome, thanks for the lib, very useful!
