### ISSUE TITLE
Format of ssh-key

### ISSUE THREAD

**Issue by te-online** [MCluck90/simple-ssh#60]
The documentation doesn't say, which format the ssk-key for privatekey login is supposed to have. Can you help on that? I always get “All configured authentication methods failed” although I can log-in through a console using the same key used. This is on a mac with node v8.8.1.

**Comment by te-online** [comment]
Okay, I figured it out. Sorry for the disturbance...

**Comment by MCluck90** [comment]
Sorry I didn't answer sooner. Glad you got it sorted out!
