### ISSUE TITLE
Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by binshuuuu** [MCluck90/simple-ssh#62]
I want to log in using the key.
Can I show you an example of how to use it?

`var sshLinux = new SSH({
		    host: IP,
		    user: NAME,
		    key : key
		});
		
		sshLinux.exec('ifconfig', {
		    err: function(stderr) {
		        console.log(stderr); // this-does-not-exist: command not found
		    },
		    out: function(stdout) {
		        console.log(IP + " - Echo : " , stdout);
		    }
		    
		}).start();
		
		sshLinux.on('error', function(err) {
		    console.log('[ SSH ]  ERROR ');
		    console.log(err);
		    sshLinux.end();
		});
		callback();`

This error has occurred.
The value of key gave the path value of id_rsa.

> 0|app      | Error: Cannot parse privateKey: Unsupported key format
> 0|app      |     at Client.connect (/usr/local/src/nodejs/dnsm_system/node_modules/ssh2/lib/client.js:230:13)
> 0|app      |     at SSH.start (/usr/local/src/nodejs/dnsm_system/node_modules/simple-ssh/lib/ssh.js:214:19)
> 0|app      |     at Object.exports.linux_shutdown (/usr/local/src/nodejs/dnsm_system/routes/node_ssh_MD.js:67:6)
> 0|app      |     at Query._callback (/usr/local/src/nodejs/dnsm_system/routes/node_mysql_MD.js:277:10)
> 0|app      |     at Query.Sequence.end (/usr/local/src/nodejs/dnsm_system/node_modules/mysql/lib/protocol/sequence                                                                         s/Sequence.js:88:24)
> 0|app      |     at Query._handleFinalResultPacket (/usr/local/src/nodejs/dnsm_system/node_modules/mysql/lib/proto                                                                         col/sequences/Query.js:139:8)
> 0|app      |     at Query.EofPacket (/usr/local/src/nodejs/dnsm_system/node_modules/mysql/lib/protocol/sequences/Q                                                                         uery.js:123:8)
> 0|app      |     at Protocol._parsePacket (/usr/local/src/nodejs/dnsm_system/node_modules/mysql/lib/protocol/Proto                                                                         col.js:279:23)
> 0|app      |     at Parser.write (/usr/local/src/nodejs/dnsm_system/node_modules/mysql/lib/protocol/Parser.js:76:1                                                                         2)
> 0|app      |     at Protocol.write (/usr/local/src/nodejs/dnsm_system/node_modules/mysql/lib/protocol/Protocol.js:                                                                         39:16)

In the above options, should the value of the key specify the path?
I have not used it yet.

Sorry.
I am a beginner.
and Thank u

**Comment by MCluck90** [comment]
The error states that the format for the key is invalid. Don't provide the path to the key, provide the value of the key. Something like:

```js
var fs = require('fs');
var key = fs.readFileSync('path/to/key/file', 'utf-8');
var sshLinux = new SSH({
  host: IP,
  user: NAME,
  key : key
});
```

If this is what you're already doing, make sure that you are loading in the right file and that it's a valid key. As a reminder, the [full API is available in the README](https://github.com/MCluck90/simple-ssh#api) and provides hints for how to use each option.

**Comment by binshuuuu** [comment]
Thank you for your reply.
I solved the problem by finding and opening the key with an absolute path. :+1:
