### ISSUE TITLE
Validate connection

### ISSUE THREAD

**Issue by YuriFontella** [MCluck90/simple-ssh#64]
Hello, simple question
Is there any way to verify that the connection was successful?

const Connection = require('simple-ssh')
ssh = new Connection({...})

if (ssh)... something like

Thanks.

**Comment by MCluck90** [comment]
You can use standard events from ssh2.

```javascript
ssh.on('ready', ...);
```

**Comment by YuriFontella** [comment]
Thanks

**Comment by ksaikiranr** [comment]
Can you please give an example?
