### ISSUE TITLE
connection using key

### ISSUE THREAD

**Issue by YuriFontella** [MCluck90/simple-ssh#66]
I have read all the topics with the related subject, it did not help.

I generated my key:
ssh-keygen -m PEM -t rsa
ssh-copy-id 

When I use this:
key: '/root/.ssh/id_rsa' I have following return ... **"Error: Can not parse privateKey: Unsupported key format"**

And so:
key: fs.readFileSync('/root/.ssh /id_rsa') ... **"Error: All configured authentication methods failed"**

I'm adding the passphrase parameter as well.
What is the correct way to connect using keys? Where am I going wrong?

**Comment by MCluck90** [comment]
It's been a while since I messed with this. `fs.readFileSync` normally returns a Buffer which might be messing it up. Try doing this:

```js
key: fs.readFileSync('/root/.ssh/id_rsa').toString()
```
