### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by MNBoy** [MCluck90/simple-ssh#73]
Hi. I have a script that opens the menu when I type the word menu. Then I have to enter a number to enter the next part.
ssh
   .exec ("menu")
   .exec (09, {
     out: console.log.bind (console),
   })
   .start ();

This code does not work for me
Because it executes 09 in the new line and outside the script
How do I fix it?
![img](https://user-images.githubusercontent.com/57574386/130367579-a294796d-e13b-422e-8541-cda1ddc2cc70.png)

**Comment by MCluck90** [comment]
Hi! Sorry, this library is very old and very simple. It's not equipped to handle that sort of flow. It just runs simple commands one after the other. You might try using the library that this is based off of: [`ssh2`](https://www.npmjs.com/package/ssh2)
